"""
Tests for the dashboard app: screening/activity/training/case models,
the bulk Excel/CSV importer, role-based data scoping, and dashboard/upload
views.
"""
import io
import datetime

import pandas as pd
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from core.models import User, Region, LocalCouncil, JamatKhana, Portfolio, Program
from .models import (
    ActivityReport, Participant, CardiacRiskAssessment, MentalHealthDASS21,
    ElderlyEyeScreening, MammogramScreening,
    TrainingProgram, TrainingAttendance, CaseRecord, CaseFollowUp, UploadBatch,
    SCREENING_MODELS,
)
from .importers import (
    normalize_header, map_row_to_canonical, to_bool, parse_date,
    get_geo, ImportError_, infer_risk_category, guess_form_type_from_sheet_name,
    import_screening_form, import_activity_report, process_upload_batch,
)
from .forms import UploadForm


def make_geo():
    region = Region.objects.create(name="Karachi")
    lc = LocalCouncil.objects.create(region=region, name="Karachi Central")
    jk = JamatKhana.objects.create(local_council=lc, name="Main JK")
    return region, lc, jk


class ModelTests(TestCase):
    def setUp(self):
        self.region, self.lc, self.jk = make_geo()

    def test_participant_uid_autogenerated(self):
        p = Participant.objects.create(
            region=self.region, local_council=self.lc, jamat_khana=self.jk,
            full_name="Ali Raza", gender="M",
        )
        self.assertTrue(p.participant_uid.startswith("P-"))

    def test_case_id_autogenerated(self):
        p = Participant.objects.create(region=self.region, local_council=self.lc, full_name="Sara", gender="F")
        case = CaseRecord.objects.create(
            region=self.region, local_council=self.lc, participant=p,
            referral_date=timezone.localdate(), referral_source="Cardiac Screening",
            reason_for_referral="High BP",
        )
        self.assertTrue(case.case_id.startswith("CASE-"))

    def test_screening_record_creation(self):
        p = Participant.objects.create(region=self.region, local_council=self.lc, full_name="Bilal", gender="M")
        record = CardiacRiskAssessment.objects.create(
            participant=p, region=self.region, local_council=self.lc,
            screening_date=timezone.localdate(), referred=True, risk_category="HIGH",
        )
        self.assertEqual(record.participant.full_name, "Bilal")
        self.assertTrue(record.referred)

    def test_activity_report_requires_portfolio_program(self):
        portfolio = Portfolio.objects.create(name="Health Screening")
        program = Program.objects.create(portfolio=portfolio, name="Cardiac Risk Assessment")
        activity = ActivityReport.objects.create(
            date=timezone.localdate(), region=self.region, local_council=self.lc,
            venue="Main JK", portfolio=portfolio, program=program,
            name_of_activity="Community Health Camp", number_of_beneficiaries=50,
        )
        self.assertEqual(activity.number_of_beneficiaries, 50)

    def test_training_attendance_updates_participant_count(self):
        portfolio = Portfolio.objects.create(name="Training")
        program = Program.objects.create(portfolio=portfolio, name="First Aid")
        training = TrainingProgram.objects.create(
            title="First Aid Training", portfolio=portfolio, program=program,
            date=timezone.localdate(), region=self.region, local_council=self.lc, trainer_name="Dr. X",
        )
        TrainingAttendance.objects.create(training=training, participant_name="Attendee 1")
        TrainingAttendance.objects.create(training=training, participant_name="Attendee 2")
        self.assertEqual(training.attendees.count(), 2)

    def test_case_follow_up_linked_to_case(self):
        p = Participant.objects.create(region=self.region, local_council=self.lc, full_name="Nadia", gender="F")
        case = CaseRecord.objects.create(
            region=self.region, local_council=self.lc, participant=p,
            referral_date=timezone.localdate(), referral_source="Mental Health", reason_for_referral="High stress score",
        )
        followup = CaseFollowUp.objects.create(case=case, follow_up_date=timezone.localdate(), consultation_details="Reviewed")
        self.assertEqual(case.follow_ups.count(), 1)
        self.assertEqual(followup.case, case)

    def test_all_screening_models_registered(self):
        self.assertEqual(len(SCREENING_MODELS), 10)


class ImporterUnitTests(TestCase):
    def test_normalize_header(self):
        self.assertEqual(normalize_header("CNIC/NIC Number"), "cnic_nic_number")
        self.assertEqual(normalize_header("  Full Name  "), "full_name")

    def test_map_row_to_canonical(self):
        row = {"full_name": "Ali", "cnic_number": "12345", "unknown_col": "xyz"}
        canonical, leftover = map_row_to_canonical(row)
        self.assertEqual(canonical.get("full_name"), "Ali")
        self.assertEqual(canonical.get("cnic"), "12345")
        self.assertIn("unknown_col", leftover)

    def test_to_bool(self):
        self.assertTrue(to_bool("Yes"))
        self.assertTrue(to_bool("yes"))
        self.assertFalse(to_bool("No"))
        self.assertFalse(to_bool(""))
        self.assertFalse(to_bool(None))

    def test_parse_date_accepts_exact_iso_format(self):
        d = parse_date("2026-01-15")
        self.assertEqual(d, datetime.date(2026, 1, 15))

    def test_parse_date_accepts_excel_midnight_timestamp_variant(self):
        # This is the exact string pandas produces for a genuine Excel date
        # cell once dtype=str forces stringification - must still be accepted.
        d = parse_date("2026-01-15 00:00:00")
        self.assertEqual(d, datetime.date(2026, 1, 15))

    def test_parse_date_rejects_other_formats_with_error(self):
        with self.assertRaises(ImportError_):
            parse_date("15/1/2026")  # DD/MM/YYYY - not the accepted format

    def test_parse_date_rejects_invalid_calendar_date_with_error(self):
        with self.assertRaises(ImportError_):
            parse_date("2026-02-29")  # 2026 is not a leap year

    def test_parse_date_rejects_blank_with_error(self):
        with self.assertRaises(ImportError_):
            parse_date("")
        with self.assertRaises(ImportError_):
            parse_date(None)

    def test_parse_date_never_silently_falls_back_to_today(self):
        # The old behavior silently returned today's date for anything
        # unparseable - confirm that's gone: a bad date now always raises.
        for bad_value in ("not-a-date", "5-March-2026", "2026/13/40"):
            with self.assertRaises(ImportError_):
                parse_date(bad_value)

    def test_infer_risk_category_detects_abnormal_as_high(self):
        leftover = {"diagnosis_findings": "Abnormal - refer to specialist"}
        self.assertEqual(infer_risk_category(leftover), "HIGH")

    def test_infer_risk_category_detects_normal_as_low(self):
        leftover = {"mammography_findings_normal_abnormal": "Normal"}
        self.assertEqual(infer_risk_category(leftover), "LOW")

    def test_infer_risk_category_detects_moderate(self):
        leftover = {"bp_bmi_status": "Moderate risk"}
        self.assertEqual(infer_risk_category(leftover), "MODERATE")

    def test_infer_risk_category_defaults_to_unknown_when_no_hint(self):
        leftover = {"some_unrelated_column": "xyz"}
        self.assertEqual(infer_risk_category(leftover), "UNKNOWN")

    def test_infer_risk_category_high_wins_over_conflicting_columns(self):
        leftover = {"bp_bmi_status": "Normal", "diagnosis_findings": "Abnormal finding"}
        self.assertEqual(infer_risk_category(leftover), "HIGH")

    def test_get_geo_raises_when_region_missing(self):
        with self.assertRaises(ImportError_):
            get_geo("NoSuchRegion", "NoSuchCouncil", "NoSuchJK")

    def test_get_geo_raises_when_local_council_missing_under_existing_region(self):
        region, lc, jk = make_geo()
        with self.assertRaises(ImportError_):
            get_geo(region.name, "NoSuchCouncil", None)

    def test_get_geo_raises_when_jamat_khana_missing_under_existing_local_council(self):
        region, lc, jk = make_geo()
        with self.assertRaises(ImportError_):
            get_geo(region.name, lc.name, "NoSuchJK")

    def test_get_geo_returns_existing_hierarchy_without_creating_anything(self):
        region, lc, jk = make_geo()
        before_regions = Region.objects.count()
        before_lcs = LocalCouncil.objects.count()
        before_jks = JamatKhana.objects.count()

        found_region, found_lc, found_jk = get_geo(region.name, lc.name, jk.name)

        self.assertEqual(found_region, region)
        self.assertEqual(found_lc, lc)
        self.assertEqual(found_jk, jk)
        # Nothing new was created - strictly looked up.
        self.assertEqual(Region.objects.count(), before_regions)
        self.assertEqual(LocalCouncil.objects.count(), before_lcs)
        self.assertEqual(JamatKhana.objects.count(), before_jks)

    def test_get_geo_jamat_khana_optional(self):
        region, lc, jk = make_geo()
        found_region, found_lc, found_jk = get_geo(region.name, lc.name, "")
        self.assertEqual(found_region, region)
        self.assertEqual(found_lc, lc)
        self.assertIsNone(found_jk)

    def test_get_geo_case_insensitive_match(self):
        region, lc, jk = make_geo()
        found_region, found_lc, found_jk = get_geo(region.name.upper(), lc.name.lower(), jk.name.upper())
        self.assertEqual(found_region, region)
        self.assertEqual(found_lc, lc)
        self.assertEqual(found_jk, jk)


class ImporterIntegrationTests(TestCase):
    """End-to-end import from a DataFrame, mirroring an uploaded Excel file.

    Region/Local Council/Jamatkhana are no longer auto-created by the
    importer (see get_geo()), so every fixture row below references
    geography that already exists via make_geo() - exactly as a real
    upload would need it to, after being added through Admin first.
    """

    def setUp(self):
        self.user = User.objects.create_user(username="importer", password="pass12345", role=User.Role.NATIONAL)
        self.region, self.lc, self.jk = make_geo()  # "Karachi" / "Karachi Central" / "Main JK"

    def test_import_cardiac_screening_success(self):
        df = pd.DataFrame([
            {
                "Date of Screening": "2026-01-15", "Full Name": "Ali Raza", "Father/Husband Name": "Ahmed",
                "CNIC": "42101-1234567-1", "Age": 45, "Gender (M/F)": "M", "Contact Number": "0300000000",
                "Region": "Karachi", "Local council": "Karachi Central", "Jamat Khana": "Main JK",
                "Referred": "Yes", "Recommendations /Additional Remarks": "Follow up",
            },
            {
                "Date of Screening": "2026-01-16", "Full Name": "", "Father/Husband Name": "",
                "CNIC": "", "Age": "", "Gender (M/F)": "", "Contact Number": "",
                "Region": "", "Local council": "", "Jamat Khana": "",
                "Referred": "No", "Recommendations /Additional Remarks": "",
            },
        ])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 1)  # second row missing Full Name -> error
        self.assertEqual(len(errors), 1)
        self.assertEqual(errors[0]["row"], 3)
        record = CardiacRiskAssessment.objects.get()
        self.assertEqual(record.participant.full_name, "Ali Raza")
        self.assertTrue(record.referred)
        self.assertEqual(record.region.name, "Karachi")

    def test_import_mental_health_dass_scores(self):
        df = pd.DataFrame([{
            "start": "2026-02-01", "Full Name": "Sana", "Gender": "F", "Age": 30, "Contact Number": "03001112222",
            "Region": "Karachi", "Local": "Karachi Central", "Depression Score": 12, "Anxiety Score": 8,
            "Stress Score": 15, "Referral": "Yes",
        }])
        success, errors = import_screening_form(df, "mental_health_dass21", self.user)
        self.assertEqual(success, 1)
        self.assertEqual(errors, [])
        rec = MentalHealthDASS21.objects.get()
        self.assertEqual(rec.depression_score, 12)
        self.assertEqual(rec.anxiety_score, 8)
        self.assertEqual(rec.stress_score, 15)

    def test_import_activity_report(self):
        df = pd.DataFrame([{
            "Date": "2026-01-10", "Region": "Karachi", "Local council": "Karachi Central",
            "Jamat Khana": "Main JK", "Portfolio": "Community Health", "Program": "Outreach",
            "Name of Activity": "Blood Donation Camp", "Number of Beneficiaries": 120,
        }])
        success, errors = import_activity_report(df, self.user)
        self.assertEqual(success, 1)
        self.assertEqual(errors, [])
        activity = ActivityReport.objects.get()
        self.assertEqual(activity.number_of_beneficiaries, 120)
        self.assertEqual(activity.portfolio.name, "Community Health")

    def test_import_activity_report_missing_required_field_errors(self):
        df = pd.DataFrame([{"Date": "2026-01-10", "Region": "Karachi"}])
        success, errors = import_activity_report(df, self.user)
        self.assertEqual(success, 0)
        self.assertEqual(len(errors), 1)

    def test_process_upload_batch_end_to_end(self):
        punjab = Region.objects.create(name="Punjab")
        LocalCouncil.objects.create(region=punjab, name="Lahore")
        df = pd.DataFrame([{
            "Date of Screening": "2026-01-20", "Full Name": "Kamran", "CNIC": "1234", "Age": 50,
            "Gender (M/F)": "M", "Region": "Punjab", "Local council": "Lahore", "Referred": "No",
        }])
        buffer = io.BytesIO()
        df.to_excel(buffer, index=False)
        buffer.seek(0)
        upload_file = SimpleUploadedFile(
            "test.xlsx", buffer.read(),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        batch = UploadBatch.objects.create(
            form_type="cardiac_risk_assessment", file=upload_file, created_by=self.user,
        )
        process_upload_batch(batch)
        batch.refresh_from_db()
        self.assertEqual(batch.status, UploadBatch.Status.COMPLETED)
        self.assertEqual(batch.success_count, 1)
        self.assertEqual(batch.error_count, 0)
        self.assertEqual(CardiacRiskAssessment.objects.count(), 1)

    def test_process_upload_batch_with_errors_status(self):
        df = pd.DataFrame([
            {
                "Date of Screening": "2026-01-20", "Full Name": "Valid Person",
                "Region": "Karachi", "Local council": "Karachi Central",
            },
            {
                "Date of Screening": "2026-01-21", "Full Name": "",
                "Region": "Karachi", "Local council": "Karachi Central",
            },
        ])
        buffer = io.BytesIO()
        df.to_excel(buffer, index=False)
        buffer.seek(0)
        upload_file = SimpleUploadedFile("test2.xlsx", buffer.read())
        batch = UploadBatch.objects.create(form_type="cardiac_risk_assessment", file=upload_file, created_by=self.user)
        process_upload_batch(batch)
        batch.refresh_from_db()
        self.assertEqual(batch.status, UploadBatch.Status.COMPLETED_WITH_ERRORS)
        self.assertEqual(batch.success_count, 1)
        self.assertEqual(batch.error_count, 1)


class RoleScopingTests(TestCase):
    """Verify that dashboards/lists only show data within a user's assigned scope."""

    def setUp(self):
        self.region_a = Region.objects.create(name="Karachi")
        self.region_b = Region.objects.create(name="Punjab")
        self.lc_a = LocalCouncil.objects.create(region=self.region_a, name="Karachi Central")
        self.lc_b = LocalCouncil.objects.create(region=self.region_b, name="Lahore")

        self.national = User.objects.create_user(username="natuser", password="pass12345", role=User.Role.NATIONAL)
        self.regional_a = User.objects.create_user(
            username="reguser_a", password="pass12345", role=User.Role.REGIONAL, region=self.region_a
        )
        self.local_b = User.objects.create_user(
            username="localuser_b", password="pass12345", role=User.Role.LOCAL, local_council=self.lc_b
        )

        p1 = Participant.objects.create(region=self.region_a, local_council=self.lc_a, full_name="Person A", gender="M")
        p2 = Participant.objects.create(region=self.region_b, local_council=self.lc_b, full_name="Person B", gender="F")
        CardiacRiskAssessment.objects.create(
            participant=p1, region=self.region_a, local_council=self.lc_a, screening_date=timezone.localdate()
        )
        CardiacRiskAssessment.objects.create(
            participant=p2, region=self.region_b, local_council=self.lc_b, screening_date=timezone.localdate()
        )

    def test_national_sees_all_screening_records(self):
        self.client.login(username="natuser", password="pass12345")
        response = self.client.get(reverse("dashboard:screening_list", args=["cardiac_risk_assessment"]))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(len(response.context["records"]), 2)

    def test_regional_sees_only_own_region_records(self):
        self.client.login(username="reguser_a", password="pass12345")
        response = self.client.get(reverse("dashboard:screening_list", args=["cardiac_risk_assessment"]))
        self.assertEqual(response.status_code, 200)
        records = response.context["records"]
        self.assertEqual(len(records), 1)
        self.assertEqual(records[0].participant.full_name, "Person A")

    def test_local_sees_only_own_local_council_records(self):
        self.client.login(username="localuser_b", password="pass12345")
        response = self.client.get(reverse("dashboard:screening_list", args=["cardiac_risk_assessment"]))
        self.assertEqual(response.status_code, 200)
        records = response.context["records"]
        self.assertEqual(len(records), 1)
        self.assertEqual(records[0].participant.full_name, "Person B")

    def test_overview_dashboard_totals_scoped_by_role(self):
        self.client.login(username="reguser_a", password="pass12345")
        response = self.client.get(reverse("dashboard:overview"))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["total_screenings"], 1)

        self.client.login(username="natuser", password="pass12345")
        response = self.client.get(reverse("dashboard:overview"))
        self.assertEqual(response.context["total_screenings"], 2)


class UploadViewPermissionTests(TestCase):
    def setUp(self):
        self.region, self.lc, self.jk = make_geo()
        self.national = User.objects.create_user(username="natupload", password="pass12345", role=User.Role.NATIONAL)
        self.viewer = User.objects.create_user(username="revieweruser", password="pass12345", role=User.Role.VIEWER)

    def test_national_can_access_upload_page(self):
        self.client.login(username="natupload", password="pass12345")
        response = self.client.get(reverse("dashboard:upload_add"))
        self.assertEqual(response.status_code, 200)

    def test_viewer_cannot_access_upload_page(self):
        self.client.login(username="revieweruser", password="pass12345")
        response = self.client.get(reverse("dashboard:upload_add"))
        self.assertEqual(response.status_code, 403)

    def test_upload_rejects_invalid_file_extension(self):
        self.client.login(username="natupload", password="pass12345")
        bad_file = SimpleUploadedFile("test.txt", b"not a spreadsheet", content_type="text/plain")
        response = self.client.post(reverse("dashboard:upload_add"), {
            "form_type": "cardiac_risk_assessment", "file": bad_file,
        })
        self.assertEqual(response.status_code, 200)  # re-rendered with form errors
        self.assertContains(response, "Only .xlsx, .xls or .csv files are supported")


class CaseManagementViewTests(TestCase):
    def setUp(self):
        self.region, self.lc, self.jk = make_geo()
        self.user = User.objects.create_user(username="casemgr", password="pass12345", role=User.Role.NATIONAL)
        self.participant = Participant.objects.create(region=self.region, local_council=self.lc, full_name="Client X", gender="M")

    def test_create_case_via_view(self):
        self.client.login(username="casemgr", password="pass12345")
        response = self.client.post(reverse("dashboard:case_add"), {
            "region": self.region.pk, "local_council": self.lc.pk, "jamat_khana": self.jk.pk,
            "participant": self.participant.pk, "referral_date": timezone.localdate().isoformat(),
            "referral_source": "Cardiac Screening", "reason_for_referral": "High BP",
            "referral_facility_doctor": "", "assigned_case_manager": "", "priority_level": "HIGH",
            "current_status": "OPEN", "case_outcome": "", "closure_status": False,
        })
        self.assertEqual(response.status_code, 302)
        self.assertEqual(CaseRecord.objects.count(), 1)

    def test_add_follow_up_to_case(self):
        case = CaseRecord.objects.create(
            region=self.region, local_council=self.lc, participant=self.participant,
            referral_date=timezone.localdate(), referral_source="Screening", reason_for_referral="Test",
        )
        self.client.login(username="casemgr", password="pass12345")
        response = self.client.post(reverse("dashboard:case_follow_up_add", args=[case.pk]), {
            "follow_up_date": timezone.localdate().isoformat(),
            "consultation_details": "Reviewed patient", "investigation_results": "", "treatment_initiated": "",
            "next_reminder_date": "",
        })
        self.assertEqual(response.status_code, 302)
        self.assertEqual(case.follow_ups.count(), 1)


# ---------------------------------------------------------------------------
# Dashboard filters + CSV/PDF export tests (added for the filter/export
# feature: filters must apply identically to on-screen analytics, CSV
# exports, and PDF exports).
# ---------------------------------------------------------------------------
from django.urls import reverse as _reverse
from .filters import DashboardFilters
from .analytics import age_bucket_label, pct, budget_utilization
from .models import BudgetAllocation as _BudgetAllocation
from core.models import Portfolio as _Portfolio, Program as _Program


class AnalyticsHelperTests(TestCase):
    def test_age_bucket_label(self):
        self.assertEqual(age_bucket_label(10), "0-17")
        self.assertEqual(age_bucket_label(25), "18-30")
        self.assertEqual(age_bucket_label(45), "31-45")
        self.assertEqual(age_bucket_label(60), "46-60")
        self.assertEqual(age_bucket_label(75), "61+")
        self.assertEqual(age_bucket_label(None), "Unknown")

    def test_pct_handles_zero_denominator(self):
        self.assertEqual(pct(5, 0), 0.0)
        self.assertEqual(pct(1, 4), 25.0)

    def test_budget_utilization_calculation(self):
        result = budget_utilization(cost_total=250, allocated_total=1000)
        self.assertEqual(result["percent"], 25.0)
        self.assertEqual(result["remaining"], 750)

    def test_budget_utilization_no_allocation(self):
        result = budget_utilization(cost_total=250, allocated_total=0)
        self.assertIsNone(result["percent"])


class DashboardFilterParsingTests(TestCase):
    def _request_with_get(self, params):
        from django.test import RequestFactory
        rf = RequestFactory()
        return rf.get("/", params)

    def test_parses_date_range(self):
        req = self._request_with_get({"date_from": "2026-01-01", "date_to": "2026-06-30"})
        filters = DashboardFilters(req)
        self.assertEqual(str(filters.date_from), "2026-01-01")
        self.assertEqual(str(filters.date_to), "2026-06-30")

    def test_invalid_date_ignored(self):
        req = self._request_with_get({"date_from": "not-a-date"})
        filters = DashboardFilters(req)
        self.assertIsNone(filters.date_from)

    def test_future_specific_date_is_clamped_to_today(self):
        """A specific-date search can't be in the future - even if someone
        crafts the URL directly (bypassing the date input's max= attribute),
        the backend clamps it to today rather than returning future data."""
        today = timezone.localdate()
        future = today + datetime.timedelta(days=30)
        req = self._request_with_get({
            "year": str(future.year), "month": str(future.month), "day": str(future.day),
        })
        filters = DashboardFilters(req)
        self.assertEqual(filters.date_from, today)
        self.assertEqual(filters.date_to, today)

    def test_future_month_range_is_clamped_to_today(self):
        today = timezone.localdate()
        future_year = today.year + 1
        req = self._request_with_get({"year": str(future_year), "month": "6"})
        filters = DashboardFilters(req)
        self.assertLessEqual(filters.date_to, today)

    def test_querystring_roundtrip(self):
        req = self._request_with_get({"region": "3", "status": "OPEN"})
        filters = DashboardFilters(req)
        qs = filters.querystring()
        self.assertIn("region=3", qs)
        self.assertIn("status=OPEN", qs)

    def test_apply_filters_to_queryset(self):
        region, lc, jk = make_geo()
        other_region = Region.objects.create(name="OtherRegion")
        p1 = Participant.objects.create(region=region, local_council=lc, full_name="A", gender="M")
        p2 = Participant.objects.create(region=other_region, local_council=lc, full_name="B", gender="F")
        CardiacRiskAssessment.objects.create(participant=p1, region=region, local_council=lc, screening_date=timezone.localdate())
        CardiacRiskAssessment.objects.create(participant=p2, region=other_region, local_council=lc, screening_date=timezone.localdate())

        req = self._request_with_get({"region": str(region.id)})
        filters = DashboardFilters(req)
        qs = filters.apply(CardiacRiskAssessment.objects.all(), date_field="screening_date", region_field="region")
        self.assertEqual(qs.count(), 1)
        self.assertEqual(qs.first().participant.full_name, "A")


class DashboardFilteredViewTests(TestCase):
    """Filters must actually change what's shown/exported, not just be
    accepted silently."""

    def setUp(self):
        self.region_a, self.lc_a, self.jk_a = make_geo()
        self.region_b = Region.objects.create(name="RegionB")
        self.lc_b = LocalCouncil.objects.create(region=self.region_b, name="LC-B")
        self.user = User.objects.create_user(username="filteruser", password="pass12345", role=User.Role.NATIONAL)

        p1 = Participant.objects.create(region=self.region_a, local_council=self.lc_a, full_name="InRegionA", gender="M")
        p2 = Participant.objects.create(region=self.region_b, local_council=self.lc_b, full_name="InRegionB", gender="F")
        CardiacRiskAssessment.objects.create(participant=p1, region=self.region_a, local_council=self.lc_a, screening_date=timezone.localdate())
        CardiacRiskAssessment.objects.create(participant=p2, region=self.region_b, local_council=self.lc_b, screening_date=timezone.localdate())

    def test_screening_dashboard_region_filter_changes_totals(self):
        self.client.login(username="filteruser", password="pass12345")
        response_all = self.client.get(_reverse("dashboard:screening_dashboard"))
        self.assertEqual(response_all.context["total"], 2)

        response_filtered = self.client.get(_reverse("dashboard:screening_dashboard"), {"region": self.region_a.id})
        self.assertEqual(response_filtered.context["total"], 1)

    def test_screening_program_filter_narrows_to_one_module(self):
        self.client.login(username="filteruser", password="pass12345")
        response = self.client.get(_reverse("dashboard:screening_dashboard"), {"screening_program": "cardiac_risk_assessment"})
        self.assertEqual(len(response.context["rows"]), 1)

    def test_case_dashboard_status_filter(self):
        p = Participant.objects.create(region=self.region_a, local_council=self.lc_a, full_name="CaseP", gender="M")
        CaseRecord.objects.create(region=self.region_a, local_council=self.lc_a, participant=p, referral_date=timezone.localdate(), referral_source="X", reason_for_referral="Y", current_status="CLOSED")
        CaseRecord.objects.create(region=self.region_a, local_council=self.lc_a, participant=p, referral_date=timezone.localdate(), referral_source="X", reason_for_referral="Y", current_status="OPEN")
        self.client.login(username="filteruser", password="pass12345")
        response = self.client.get(_reverse("dashboard:case_dashboard"), {"status": "CLOSED"})
        self.assertEqual(response.context["total_cases"], 1)


class ExportViewTests(TestCase):
    def setUp(self):
        self.region, self.lc, self.jk = make_geo()
        self.user = User.objects.create_user(username="exportuser", password="pass12345", role=User.Role.NATIONAL)
        p = Participant.objects.create(region=self.region, local_council=self.lc, full_name="ExportP", gender="M")
        CardiacRiskAssessment.objects.create(participant=p, region=self.region, local_council=self.lc, screening_date=timezone.localdate())

        portfolio = _Portfolio.objects.create(name="Community Health")
        program = _Program.objects.create(portfolio=portfolio, name="Outreach")
        ActivityReport.objects.create(
            date=timezone.localdate(), region=self.region, local_council=self.lc, venue="V",
            portfolio=portfolio, program=program, name_of_activity="Camp", number_of_beneficiaries=10,
        )
        training = TrainingProgram.objects.create(
            title="T1", portfolio=portfolio, program=program, date=timezone.localdate(),
            region=self.region, local_council=self.lc, trainer_name="Dr. Y",
        )
        CaseRecord.objects.create(
            region=self.region, local_council=self.lc, participant=p, referral_date=timezone.localdate(),
            referral_source="Screening", reason_for_referral="Test",
        )

    def test_overview_csv_export(self):
        self.client.login(username="exportuser", password="pass12345")
        response = self.client.get(_reverse("dashboard:overview_export"))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/csv")

    def test_overview_pdf_export(self):
        self.client.login(username="exportuser", password="pass12345")
        response = self.client.get(_reverse("dashboard:overview_export_pdf"))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/pdf")
        self.assertTrue(response.content.startswith(b"%PDF"))

    def test_activity_csv_and_pdf_export(self):
        self.client.login(username="exportuser", password="pass12345")
        csv_resp = self.client.get(_reverse("dashboard:activity_export"))
        self.assertEqual(csv_resp.status_code, 200)
        pdf_resp = self.client.get(_reverse("dashboard:activity_export_pdf"))
        self.assertEqual(pdf_resp.status_code, 200)
        self.assertTrue(pdf_resp.content.startswith(b"%PDF"))

    def test_screening_dashboard_csv_and_pdf_export(self):
        self.client.login(username="exportuser", password="pass12345")
        csv_resp = self.client.get(_reverse("dashboard:screening_dashboard_export"))
        self.assertEqual(csv_resp.status_code, 200)
        pdf_resp = self.client.get(_reverse("dashboard:screening_export_pdf"))
        self.assertEqual(pdf_resp.status_code, 200)
        self.assertTrue(pdf_resp.content.startswith(b"%PDF"))

    def test_training_csv_and_pdf_export(self):
        self.client.login(username="exportuser", password="pass12345")
        csv_resp = self.client.get(_reverse("dashboard:training_export"))
        self.assertEqual(csv_resp.status_code, 200)
        pdf_resp = self.client.get(_reverse("dashboard:training_export_pdf"))
        self.assertEqual(pdf_resp.status_code, 200)
        self.assertTrue(pdf_resp.content.startswith(b"%PDF"))

    def test_case_csv_and_pdf_export(self):
        self.client.login(username="exportuser", password="pass12345")
        csv_resp = self.client.get(_reverse("dashboard:case_export"))
        self.assertEqual(csv_resp.status_code, 200)
        pdf_resp = self.client.get(_reverse("dashboard:case_export_pdf"))
        self.assertEqual(pdf_resp.status_code, 200)
        self.assertTrue(pdf_resp.content.startswith(b"%PDF"))

    def test_pdf_export_respects_region_filter(self):
        """A PDF requested with a region filter that excludes all data should
        still succeed (0 rows) rather than error."""
        other_region = Region.objects.create(name="EmptyRegion")
        self.client.login(username="exportuser", password="pass12345")
        response = self.client.get(_reverse("dashboard:screening_export_pdf"), {"region": other_region.id})
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.content.startswith(b"%PDF"))


class BudgetAllocationTests(TestCase):
    def setUp(self):
        self.region, self.lc, self.jk = make_geo()
        self.portfolio = _Portfolio.objects.create(name="Health Screening")
        self.national = User.objects.create_user(username="budgetnat", password="pass12345", role=User.Role.NATIONAL)
        self.regional = User.objects.create_user(username="budgetreg", password="pass12345", role=User.Role.REGIONAL, region=self.region)

    def test_national_only_can_add_budget(self):
        self.client.login(username="budgetreg", password="pass12345")
        response = self.client.get(_reverse("dashboard:budget_add"))
        self.assertEqual(response.status_code, 403)

        self.client.login(username="budgetnat", password="pass12345")
        response = self.client.get(_reverse("dashboard:budget_add"))
        self.assertEqual(response.status_code, 200)

    def test_national_level_allocation_visible_to_regional_scope(self):
        _BudgetAllocation.objects.create(portfolio=self.portfolio, region=None, fiscal_year=2026, allocated_amount=5000)
        from .utils import scope_budget_qs
        qs = scope_budget_qs(self.regional, _BudgetAllocation.objects.all())
        self.assertEqual(qs.count(), 1)


# ---------------------------------------------------------------------------
# Strict geography lookup on bulk upload (no auto-creation - see get_geo())
# and the form-type-specific downloadable upload templates.
# ---------------------------------------------------------------------------
class StrictGeoImportTests(TestCase):
    """Bulk upload must cross-check Region/Local Council/Jamatkhana against
    existing records only; unknown geography is a row-level error, not an
    auto-created record."""

    def setUp(self):
        self.user = User.objects.create_user(username="strictgeo", password="pass12345", role=User.Role.NATIONAL)
        self.region, self.lc, self.jk = make_geo()

    def test_screening_row_with_unknown_region_errors_without_creating_it(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Someone New",
            "Region": "BrandNewRegion", "Local council": "SomeCouncil",
        }])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 0)
        self.assertEqual(len(errors), 1)
        self.assertIn("BrandNewRegion", errors[0]["error"])
        self.assertFalse(Region.objects.filter(name="BrandNewRegion").exists())

    def test_screening_row_with_unknown_local_council_errors_without_creating_it(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Someone New",
            "Region": self.region.name, "Local council": "NotARealCouncil",
        }])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 0)
        self.assertEqual(len(errors), 1)
        self.assertIn("NotARealCouncil", errors[0]["error"])
        self.assertFalse(LocalCouncil.objects.filter(name="NotARealCouncil").exists())

    def test_screening_row_with_known_geography_succeeds(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Known Geo Person",
            "Region": self.region.name, "Local council": self.lc.name, "Jamat Khana": self.jk.name,
        }])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 1)
        self.assertEqual(errors, [])

    def test_activity_report_row_with_unknown_geography_errors(self):
        df = pd.DataFrame([{
            "Date": "2026-01-10", "Region": "GhostRegion", "Local council": "GhostCouncil",
            "Name of Activity": "Some Camp", "Number of Beneficiaries": 10,
        }])
        success, errors = import_activity_report(df, self.user)
        self.assertEqual(success, 0)
        self.assertEqual(len(errors), 1)
        self.assertFalse(Region.objects.filter(name="GhostRegion").exists())


class UploadTemplateDownloadTests(TestCase):
    def setUp(self):
        self.national = User.objects.create_user(username="tplnat", password="pass12345", role=User.Role.NATIONAL)
        self.viewer = User.objects.create_user(username="tplviewer", password="pass12345", role=User.Role.VIEWER)

    def test_uploader_can_download_template_for_valid_form_type(self):
        self.client.login(username="tplnat", password="pass12345")
        response = self.client.get(_reverse("dashboard:upload_template", args=["cardiac_risk_assessment"]))
        self.assertEqual(response.status_code, 200)
        self.assertEqual(
            response["Content-Type"],
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    def test_template_covers_every_form_type(self):
        self.client.login(username="tplnat", password="pass12345")
        for form_type, _label in UploadBatch.FormType.choices:
            response = self.client.get(_reverse("dashboard:upload_template", args=[form_type]))
            self.assertEqual(response.status_code, 200, f"template download failed for {form_type}")

    def test_unknown_form_type_redirects_with_message(self):
        self.client.login(username="tplnat", password="pass12345")
        response = self.client.get(_reverse("dashboard:upload_template", args=["not_a_real_type"]))
        self.assertEqual(response.status_code, 302)

    def test_viewer_cannot_download_template(self):
        self.client.login(username="tplviewer", password="pass12345")
        response = self.client.get(_reverse("dashboard:upload_template", args=["cardiac_risk_assessment"]))
        self.assertEqual(response.status_code, 403)


class StrictDateAndRiskCategoryIntegrationTests(TestCase):
    """End-to-end (through import_screening_form / import_activity_report,
    not just the unit-level parse_date/infer_risk_category functions) checks
    that a bad date errors the row instead of defaulting to today, and that
    a risk/finding column both sets the structured risk_category field AND
    is still preserved verbatim in `details` - no data lost either way."""

    def setUp(self):
        self.user = User.objects.create_user(username="dateuser", password="pass12345", role=User.Role.NATIONAL)
        self.region, self.lc, self.jk = make_geo()

    def test_bad_date_format_errors_the_row_not_defaults_to_today(self):
        df = pd.DataFrame([{
            "Date of Screening": "15/1/2026",  # DD/MM/YYYY - not accepted
            "Full Name": "Someone", "Region": self.region.name, "Local council": self.lc.name,
        }])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 0)
        self.assertEqual(len(errors), 1)
        self.assertIn("YYYY-MM-DD", errors[0]["error"])
        self.assertEqual(CardiacRiskAssessment.objects.count(), 0)

    def test_invalid_calendar_date_errors_the_row(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-02-29",  # 2026 is not a leap year
            "Full Name": "Someone", "Region": self.region.name, "Local council": self.lc.name,
        }])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 0)
        self.assertEqual(len(errors), 1)

    def test_correctly_formatted_date_imports_with_exact_date_preserved(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-03-05",
            "Full Name": "Someone", "Region": self.region.name, "Local council": self.lc.name,
        }])
        success, errors = import_screening_form(df, "cardiac_risk_assessment", self.user)
        self.assertEqual(success, 1)
        self.assertEqual(errors, [])
        record = CardiacRiskAssessment.objects.get()
        self.assertEqual(record.screening_date, datetime.date(2026, 3, 5))

    def test_eye_screening_diagnosis_findings_sets_risk_category_and_is_kept_in_details(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Eye Patient",
            "Region": self.region.name, "Local council": self.lc.name,
            "Diagnosis/Findings": "Abnormal - cataract detected",
        }])
        success, errors = import_screening_form(df, "elderly_eye_screening", self.user)
        self.assertEqual(success, 1)
        self.assertEqual(errors, [])
        record = ElderlyEyeScreening.objects.get()
        self.assertEqual(record.risk_category, "HIGH")
        # The raw column must still be present in details - never dropped.
        self.assertIn("diagnosis_findings", record.details)
        self.assertIn("Abnormal", record.details["diagnosis_findings"])

    def test_mammogram_findings_normal_sets_low_risk_and_is_kept_in_details(self):
        df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Mammo Patient",
            "Region": self.region.name, "Local council": self.lc.name,
            "Mammography Findings Normal/Abnormal": "Normal",
        }])
        success, errors = import_screening_form(df, "mammogram_screening", self.user)
        self.assertEqual(success, 1)
        record = MammogramScreening.objects.get()
        self.assertEqual(record.risk_category, "LOW")
        self.assertIn("mammography_findings_normal_abnormal", record.details)


class MultiSheetUploadTests(TestCase):
    """A workbook with one tab per screening/report type (the common
    Kobo/AKHSP export shape) can be uploaded as a single file: each sheet
    is matched to its Form Type by its tab name and processed
    automatically, instead of only ever reading the first sheet."""

    def setUp(self):
        self.user = User.objects.create_user(username="multisheet", password="pass12345", role=User.Role.NATIONAL)
        self.region, self.lc, self.jk = make_geo()

    def _build_workbook(self, sheets):
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
            for name, df in sheets.items():
                df.to_excel(writer, sheet_name=name, index=False)
        buffer.seek(0)
        return SimpleUploadedFile(
            "multi.xlsx", buffer.read(),
            content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

    def test_guess_form_type_matches_real_world_sheet_names(self):
        # These are the exact tab names from a real Kobo/AKHSP-style export.
        cases = {
            "Cardiac Risk Assessment": "cardiac_risk_assessment",
            "School H&A Data": "adolescent_health_screening",
            "CBE Screeening": "clinical_breast_examination",
            "Dass Screening": "mental_health_dass21",
            "ICOPE": "elderly_neurological_assessment",
            "eye screening data": "elderly_eye_screening",
            "Camp Screening": "adult_health_screening",
            "Memogram": "mammogram_screening",
            "HBA1C": "hba1c_screening",
        }
        for sheet_name, expected in cases.items():
            self.assertEqual(guess_form_type_from_sheet_name(sheet_name), expected, sheet_name)

    def test_guess_form_type_returns_none_for_unrecognized_name(self):
        self.assertIsNone(guess_form_type_from_sheet_name("Cover Page"))
        self.assertIsNone(guess_form_type_from_sheet_name("Notes"))
        self.assertIsNone(guess_form_type_from_sheet_name(""))

    def test_multi_sheet_workbook_processes_each_sheet_and_flags_unmatched(self):
        cardiac_df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Sheet One Person",
            "Region": self.region.name, "Local council": self.lc.name,
        }])
        unmatched_df = pd.DataFrame([{"Some Column": "value"}])
        upload_file = self._build_workbook({
            "Cardiac Risk Assessment": cardiac_df,
            "Random Notes": unmatched_df,
        })
        batch = UploadBatch.objects.create(form_type="cardiac_risk_assessment", file=upload_file, created_by=self.user)
        process_upload_batch(batch)
        batch.refresh_from_db()

        self.assertEqual(batch.form_type, "MULTI_SHEET")
        self.assertEqual(batch.success_count, 1)
        self.assertEqual(CardiacRiskAssessment.objects.count(), 1)
        self.assertTrue(any("Random Notes" in e["error"] for e in batch.error_log))
        self.assertEqual(batch.status, UploadBatch.Status.COMPLETED_WITH_ERRORS)

    def test_multi_sheet_workbook_processes_all_matched_sheets_not_just_first(self):
        cardiac_df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Cardiac Person",
            "Region": self.region.name, "Local council": self.lc.name,
        }])
        dass_df = pd.DataFrame([{
            "start": "2026-01-16", "Full Name": "Dass Person",
            "Region": self.region.name, "Local council": self.lc.name,
            "Depression Score": 10, "Anxiety Score": 5, "Stress Score": 8,
        }])
        upload_file = self._build_workbook({
            "Cardiac Risk Assessment": cardiac_df,
            "Dass Screening": dass_df,
        })
        batch = UploadBatch.objects.create(form_type="cardiac_risk_assessment", file=upload_file, created_by=self.user)
        process_upload_batch(batch)
        batch.refresh_from_db()

        self.assertEqual(batch.success_count, 2)
        self.assertEqual(CardiacRiskAssessment.objects.count(), 1)
        self.assertEqual(MentalHealthDASS21.objects.count(), 1)

    def test_single_sheet_workbook_keeps_manually_selected_form_type(self):
        cardiac_df = pd.DataFrame([{
            "Date of Screening": "2026-01-15", "Full Name": "Single Sheet Person",
            "Region": self.region.name, "Local council": self.lc.name,
        }])
        upload_file = self._build_workbook({"Sheet1": cardiac_df})
        batch = UploadBatch.objects.create(form_type="cardiac_risk_assessment", file=upload_file, created_by=self.user)
        process_upload_batch(batch)
        batch.refresh_from_db()

        self.assertEqual(batch.form_type, "cardiac_risk_assessment")
        self.assertEqual(batch.success_count, 1)

    def test_blank_padding_rows_are_not_counted_or_errored(self):
        df = pd.DataFrame([
            {"Date of Screening": "2026-01-15", "Full Name": "Real Person",
             "Region": self.region.name, "Local council": self.lc.name},
            {"Date of Screening": "", "Full Name": "", "Region": "", "Local council": ""},
            {"Date of Screening": "", "Full Name": "", "Region": "", "Local council": ""},
        ])
        upload_file = self._build_workbook({"Sheet1": df})
        batch = UploadBatch.objects.create(form_type="cardiac_risk_assessment", file=upload_file, created_by=self.user)
        process_upload_batch(batch)
        batch.refresh_from_db()

        self.assertEqual(batch.total_rows, 1)
        self.assertEqual(batch.success_count, 1)
        self.assertEqual(batch.error_count, 0)

    def test_upload_form_excludes_multi_sheet_choice(self):
        form = UploadForm()
        choice_values = [v for v, _ in form.fields["form_type"].choices]
        self.assertNotIn("MULTI_SHEET", choice_values)
