# Generated by Django 6.1 on 2026-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbatch',
            name='form_type',
            field=models.CharField(choices=[('ACTIVITY_REPORT', 'Activity Report'), ('cardiac_risk_assessment', 'Cardiac Risk Assessment'), ('mental_health_dass21', 'Mental Health (DASS-21)'), ('clinical_breast_examination', 'Clinical Breast Examination'), ('mammogram_screening', 'Mammogram Screening'), ('elderly_eye_screening', 'Elderly Eye Screening'), ('adolescent_health_screening', 'Adolescent Health Screening'), ('hba1c_screening', 'HbA1c Screening'), ('nutrition_assessment', 'Nutrition Assessment'), ('elderly_neurological_assessment', 'Elderly Neurological Assessment'), ('adult_health_screening', 'Adult Health Screening'), ('TRAINING_ATTENDANCE', 'Training Attendance')], max_length=50),
        ),
    ]
