"""
Tests for the core app: custom user model, roles, geography, permissions,
authentication, and user-management views.
"""
from django.core.exceptions import ValidationError
from django.test import TestCase, Client
from django.urls import reverse

from .models import User, Region, LocalCouncil, JamatKhana, AuditLog


class GeographyModelTests(TestCase):
    def test_region_code_autogenerated(self):
        region = Region.objects.create(name="Karachi")
        self.assertEqual(region.code, "KAR")

    def test_local_council_str(self):
        region = Region.objects.create(name="Sindh")
        lc = LocalCouncil.objects.create(region=region, name="Hyderabad")
        self.assertIn("Hyderabad", str(lc))
        self.assertIn("Sindh", str(lc))

    def test_jamatkhana_region_property(self):
        region = Region.objects.create(name="Punjab")
        lc = LocalCouncil.objects.create(region=region, name="Lahore")
        jk = JamatKhana.objects.create(local_council=lc, name="Model Town JK")
        self.assertEqual(jk.region, region)

    def test_unique_constraints(self):
        region = Region.objects.create(name="Balochistan")
        LocalCouncil.objects.create(region=region, name="Quetta")
        with self.assertRaises(Exception):
            LocalCouncil.objects.create(region=region, name="Quetta")


class UserModelTests(TestCase):
    def setUp(self):
        self.region = Region.objects.create(name="Karachi")
        self.local_council = LocalCouncil.objects.create(region=self.region, name="Karachi Central")

    def test_national_user_scope(self):
        user = User.objects.create_user(username="national1", password="pass12345", role=User.Role.NATIONAL)
        self.assertTrue(user.is_national)
        self.assertEqual(user.scope_label(), "All Regions")
        self.assertTrue(user.can_upload)
        self.assertTrue(user.can_manage_users)

    def test_regional_user_requires_region(self):
        user = User(username="regional1", role=User.Role.REGIONAL)
        with self.assertRaises(ValidationError):
            user.full_clean()

    def test_regional_user_valid_with_region(self):
        user = User.objects.create_user(
            username="regional2", password="pass12345", role=User.Role.REGIONAL, region=self.region
        )
        user.full_clean()  # should not raise
        self.assertTrue(user.is_regional)
        self.assertEqual(user.scope_label(), str(self.region))

    def test_local_user_requires_local_council(self):
        user = User(username="local1", role=User.Role.LOCAL)
        with self.assertRaises(ValidationError):
            user.full_clean()

    def test_data_entry_user_scope(self):
        user = User.objects.create_user(
            username="entry1", password="pass12345", role=User.Role.DATA_ENTRY, local_council=self.local_council
        )
        self.assertTrue(user.is_local)
        self.assertTrue(user.can_upload)
        self.assertFalse(user.can_manage_users)
        self.assertEqual(user.scope_label(), str(self.local_council))

    def test_superuser_is_always_national(self):
        user = User.objects.create_superuser(username="admin1", password="pass12345", email="a@a.com")
        self.assertTrue(user.is_national)


class AuthenticationViewTests(TestCase):
    def setUp(self):
        self.client = Client()
        self.user = User.objects.create_user(username="tester", password="pass12345", role=User.Role.NATIONAL)

    def test_login_page_loads(self):
        response = self.client.get(reverse("core:login"))
        self.assertEqual(response.status_code, 200)

    def test_login_success_redirects_to_dashboard(self):
        response = self.client.post(reverse("core:login"), {"username": "tester", "password": "pass12345"})
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse("dashboard:overview"))

    def test_login_failure_shows_error(self):
        response = self.client.post(reverse("core:login"), {"username": "tester", "password": "wrongpass"})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Invalid username or password")

    def test_logout_creates_audit_entry_and_redirects(self):
        self.client.login(username="tester", password="pass12345")
        response = self.client.get(reverse("core:logout"))
        self.assertEqual(response.status_code, 302)
        self.assertTrue(AuditLog.objects.filter(action=AuditLog.Action.LOGOUT).exists())

    def test_login_creates_audit_entry(self):
        self.client.post(reverse("core:login"), {"username": "tester", "password": "pass12345"})
        self.assertTrue(AuditLog.objects.filter(action=AuditLog.Action.LOGIN, user=self.user).exists())

    def test_profile_requires_login(self):
        response = self.client.get(reverse("core:profile"))
        self.assertEqual(response.status_code, 302)  # redirected to login

    def test_profile_loads_when_authenticated(self):
        self.client.login(username="tester", password="pass12345")
        response = self.client.get(reverse("core:profile"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "tester")


class UserManagementPermissionTests(TestCase):
    """National admins can manage users; other roles cannot."""

    def setUp(self):
        self.region = Region.objects.create(name="Karachi")
        self.local_council = LocalCouncil.objects.create(region=self.region, name="Karachi Central")
        self.national = User.objects.create_user(username="natadmin", password="pass12345", role=User.Role.NATIONAL)
        self.regional = User.objects.create_user(
            username="reguser", password="pass12345", role=User.Role.REGIONAL, region=self.region
        )
        self.data_entry = User.objects.create_user(
            username="entryuser", password="pass12345", role=User.Role.DATA_ENTRY, local_council=self.local_council
        )

    def test_national_can_access_user_list(self):
        self.client.login(username="natadmin", password="pass12345")
        response = self.client.get(reverse("core:user_list"))
        self.assertEqual(response.status_code, 200)

    def test_regional_cannot_access_user_list(self):
        self.client.login(username="reguser", password="pass12345")
        response = self.client.get(reverse("core:user_list"))
        self.assertEqual(response.status_code, 403)

    def test_data_entry_cannot_access_user_list(self):
        self.client.login(username="entryuser", password="pass12345")
        response = self.client.get(reverse("core:user_list"))
        self.assertEqual(response.status_code, 403)

    def test_anonymous_redirected_to_login(self):
        response = self.client.get(reverse("core:user_list"))
        self.assertEqual(response.status_code, 302)

    def test_national_can_create_user(self):
        self.client.login(username="natadmin", password="pass12345")
        response = self.client.post(reverse("core:user_add"), {
            "username": "newuser1",
            "first_name": "New",
            "last_name": "User",
            "email": "new@example.com",
            "phone_number": "",
            "designation": "",
            "role": User.Role.DATA_ENTRY,
            "region": "",
            "local_council": self.local_council.pk,
            "password1": "SuperSecret123!",
            "password2": "SuperSecret123!",
        })
        self.assertEqual(response.status_code, 302)
        self.assertTrue(User.objects.filter(username="newuser1").exists())

    def test_regional_cannot_create_user(self):
        self.client.login(username="reguser", password="pass12345")
        response = self.client.get(reverse("core:user_add"))
        self.assertEqual(response.status_code, 403)


class AuditLogTests(TestCase):
    def setUp(self):
        self.national = User.objects.create_user(username="natadmin2", password="pass12345", role=User.Role.NATIONAL)

    def test_audit_log_view_requires_national(self):
        self.client.login(username="natadmin2", password="pass12345")
        response = self.client.get(reverse("core:audit_log"))
        self.assertEqual(response.status_code, 200)
